### PR TITLE
restrict visibility of attribute name to protected

### LINKED ISSUE #38: NomadCloud's private "name" field shadows its public parent and produces NullPointerException in other plugins
[NomadCloud](https://github.com/jenkinsci/nomad-plugin/blob/master/src/main/java/org/jenkinsci/plugins/nomad/NomadCloud.java#L29) redefines the `name` attribute as a private, whereas [the parent class](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/slaves/Cloud.java#L99) (via `AbastractCloudImpl`) defines it as public.

This creates a situation where:

1. When Jenkins starts, it picks up the configuration from its configuration file
1. It loads the relevant `Cloud`s objects configured and deserialize somehow the configuration into these objects
1. This populate the private `name` field of the concrete `NomadCloud` object, and shadows the public `name` field of the parent class
1. There's now a situation where, considering we have a `cloud` object of type `NomadCloud`:
  * `cloud.name` is null (it's the public `name` field of the parent class)
  * `cloud.getName()` returns the actual name of the `NomadCloud` object

This triggers unrelated failures many other Cloud-like plugins which are calling the public [`Jenkins.CloudList.getByName()`](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/model/Jenkins.java#L508) method because the `name` field is now `null` and `c.name.equals(name)` raises a `NullPointerException`.

### PR DESCRIPTION
**Pull request by phedoreanu**
Hopefully fixes #38.

### CODE REVIEW

File: src/main/java/org/jenkinsci/plugins/nomad/NomadCloud.java [hunk 1]
```diff
@@ -26,7 +26,7 @@
 
     private static final Logger LOGGER = Logger.getLogger(NomadCloud.class.getName());
     private final List<? extends NomadSlaveTemplate> templates;
-    private final String name;
+    protected final String name;
```
Comment (multani) [inline src/main/java/org/jenkinsci/plugins/nomad/NomadCloud.java]: I think this should be removed altogether, it's defined in the parent class and I don't think there's a special need to redefine it here?

Comment (phedoreanu) [reply src/main/java/org/jenkinsci/plugins/nomad/NomadCloud.java]: Removed.

Comment (multani) [reply src/main/java/org/jenkinsci/plugins/nomad/NomadCloud.java]: I haven't tested the fix but that looks good to me
